FROM node:10

MAINTAINER Alexandre Casanova--Franger

RUN mkdir -p /home/node/app/
WORKDIR /home/node/app/

ENV PATH /home/node/app/node_modules/.bin:$PATH

COPY package.json /home/node/app/package.json
RUN npm install
RUN npm install -g @angular/cli@7.1.1
RUN npm install -g typescript
RUN npm install -g rxjs rxjs-compat
RUN npm install bootstrap font-awesome

COPY . /home/node/app

EXPOSE $PORT
CMD ng serve --host 0.0.0.0
