swagger: '2.0'
info:
  description: Server Playlist-Generator
  version: 0.0.1
  title: Server Playlist-Generator
tags:
  - name: user
    description: Operations about user
schemes:
  - http
paths:
  /users:
    get:
      tags:
        - user
      summary: Get all the users
      description: Return a json list of all the users in the database.
      operationId: loginUser
      produces:
        - application/json
      responses:
        default:
          description: successful operation
          schema:
            $ref: '#/definitions/User'
    delete:
      tags:
        - user
      summary: Delete all users
      description: Delete every user in the database
      operationId: deleteUsers
      responses:
        '200':
          description: successful operation.
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: Add a new user in the database.
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: successful operation - the user is created.
        '409':
          description: Conflict - the user already exists.
  /user/{firstname}/{lastname}:
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done if a user with the given name already exists.
      operationId: updateUser
      produces:
        - application/json
      parameters:
        - name: firstname
          in: path
          description: The firstname that needs to be updated
          required: true
          type: string
        - name: lastname
          in: path
          description: The lastname that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
        '404':
          description: User that needs to be updated is not found
        '409':
          description: Conflict - the user already exists.
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done a user with the given name already exists.
      operationId: deleteUser
      produces:
        - application/json
      parameters:
        - name: firstname
          in: path
          description: The name that needs to be deleted
          required: true
          type: string
        - name: lastname
          in: path
          description: The name that needs to be updated
          required: true
          type: string
      responses:
        '200':
          description: successful operation.
        '404':
          description: User that needs to be deleted is not found
definitions:
  User:
    type: object
    properties:
      firstname:
        type: string
      lastname:
        type: string
