FROM node:10

MAINTAINER Lucas Vivas

RUN mkdir -p /home/node/app/
WORKDIR /home/node/app/

COPY .  ./

RUN npm init -y
RUN npm install express morgan cors mongoose eslint body-parser

EXPOSE $PORT
CMD npm run start
